import { getState, saveState, id, todayKey, escapeHtml as esc } from './supabaseClient.js?v=9';
import { weekDates, timedEvents } from './plannerView.js?v=2';
import { weekdays, dateKey, shiftDate, minutes, clock, validateEvent, occursOn, dayEntries, monthDays, parseTimetable, reviewPlan, todaySummary } from './semesterStore.js?v=2';
import { writeNote } from './notesStore.js';

export function initializeSemesterPlanner(userId, onChange = () => {}, {view='planner'} = {}) {
  const root=document.querySelector('#workspace-view'), today=todayKey();
  let selected=today, month=today.slice(0,7)+'-01', mode=matchMedia('(max-width:800px)').matches?'month':'week', query='', kind='all', current=null, editing=null, reviews=[];
  const label=(day,options={month:'short',day:'numeric'})=>new Date(day+'T12:00:00').toLocaleDateString('en-US',options);
  const color=e=>'tone-'+(Number.isInteger(e.color)&&e.color>=0&&e.color<6?e.color:4);
  const semester=()=>getState().settings?.[userId]?.semester||{start:today.slice(0,4)+'-09-01',end:today.slice(0,4)+'-12-20'};
  const matches=e=>(kind==='all'||e.kind===kind)&&(!query||(e.title+' '+(e.location||'')).toLocaleLowerCase().includes(query));
  const entries=day=>dayEntries(getState(),userId,day).filter(matches);
  const ownedTasks=()=>{const s=getState();return s.tasks.filter(t=>t.user_id===userId&&s.projects.some(p=>p.id===t.project_id&&p.user_id===userId));};
  const button=(text,attrs='')=>`<button type="button" class="cal-button" ${attrs}>${text}</button>`;
  root.classList.add('semester-workspace');
  root.classList.toggle('is-today-workspace',view==='today');
  root.innerHTML=`<div class="semester-toolbar"><div class="cal-segments" aria-label="Calendar view">${['week','month','agenda'].map(m=>button(m[0].toUpperCase()+m.slice(1),`data-mode="${m}" aria-pressed="${mode===m}"`)).join('')}</div><div class="calendar-actions">${button('Semester','data-action="semester"')}${button('＋ Event','data-action="new-event"')}</div></div>
    <div class="semester-layout"><aside class="calendar-sidebar"><section class="mini-month" aria-label="Date picker"></section><section class="selected-day"><div class="calendar-section-heading"><h2 id="selected-day-label"></h2>${button('＋','data-action="new-task" aria-label="Add task on selected day"')}</div><div id="selected-day-items"></div></section><details class="task-inbox" id="calendar-overdue"><summary>Overdue <span id="calendar-overdue-count"></span></summary><div id="calendar-overdue-list"></div></details><details class="task-inbox"><summary>Inbox <span id="inbox-count"></span></summary><div id="inbox-list"></div></details></aside>
    <section class="semester-main"><header class="calendar-heading"><div><p id="calendar-subtitle"></p><h2 id="calendar-period"></h2></div><div class="calendar-paging">${button('‹','data-action="previous" aria-label="Previous period"')}${button('Today','data-action="today"')}${button('›','data-action="next" aria-label="Next period"')}</div></header>
      <div class="calendar-filter"><div class="calendar-kinds">${[['all','All'],['class','Classes'],['review','Review'],['task','Tasks'],['study','Study']].map(([k,text])=>button(text,`data-kind="${k}" aria-pressed="${k==='all'}"`)).join('')}</div><input type="search" id="calendar-search" aria-label="Search calendar" placeholder="Search"></div><div id="semester-grid"></div><footer class="calendar-foot"><span id="semester-caption"></span>${button('Import timetable','data-action="import"')}</footer></section></div><div id="today-overview" ${view==='today'?'':'hidden'}></div>`;
  document.body.insertAdjacentHTML('beforeend',`
    <dialog id="semester-event" class="modal calendar-modal"><form id="semester-event-form"><header><p class="eyebrow">Calendar</p><h2 id="event-editor-title">New event</h2></header><label>Name<input name="title" required maxlength="120"></label><div class="schedule-fields"><label>Type<select name="kind"><option value="class">Class</option><option value="study">Study</option><option value="event">Personal</option></select></label><label>Location<input name="location" maxlength="80" placeholder="Room or link"></label><label>Date<input name="first_date" type="date" required></label><label>Repeat<select name="repeat"><option value="none">Once</option><option value="weekly">Weekly</option><option value="daily">Daily</option></select></label><label>Start<input name="start_time" type="time" required></label><label>End<input name="end_time" type="time" required></label><label class="recurrence-field">Weekday<select name="weekday">${weekdays.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select></label><label class="recurrence-field">Until<input name="last_date" type="date"></label></div><fieldset class="calendar-swatches"><legend>Color</legend>${['Rose','Butter','Mint','Sky','Lilac','Peach'].map((text,i)=>`<label class="tone-${i}" title="${text}"><input type="radio" name="color" value="${i}" ${i===0?'checked':''} aria-label="${text}"></label>`).join('')}</fieldset><p class="form-error" role="alert"></p><div class="form-actions">${button('Pause series','id="pause-series" hidden')}${button('Restore skipped dates','id="restore-skipped" hidden')}${button('Cancel','data-close') }<button class="button button-primary" type="submit">Save event</button></div></form></dialog>
    <dialog id="semester-settings" class="modal calendar-modal"><form id="semester-settings-form"><p class="eyebrow">Timetable</p><h2>Semester</h2><div class="schedule-fields"><label>Start date<input type="date" name="start" required></label><label>End date<input type="date" name="end" required></label></div><p class="calendar-hint">Applies to repeating classes. Study sessions and tasks keep their dates.</p><div id="semester-class-list"></div><p class="form-error" role="alert"></p><div class="form-actions">${button('Cancel','data-close')}<button class="button button-primary" type="submit">Save semester</button></div></form></dialog>
    <dialog id="semester-import" class="modal calendar-modal"><form id="semester-import-form"><p class="eyebrow">Weekly timetable</p><h2>Import timetable</h2><div class="schedule-fields"><label>Semester starts<input type="date" name="start" required></label><label>Semester ends<input type="date" name="end" required></label></div><label>Tab-separated rows<textarea name="rows" rows="8" required spellcheck="false" placeholder="Course&#9;Mon&#9;09:00&#9;10:15&#9;Room"></textarea></label><p class="calendar-hint">Name · Mon–Sun · Start · End · Room · Type (class, study, event). One event per line. Review the preview before adding.</p><div id="import-preview"></div><p class="form-error" role="alert"></p><div class="form-actions">${button('Cancel','data-close')}<button type="submit" class="button button-primary" id="import-submit">Preview</button></div></form></dialog>
    <dialog id="calendar-detail" class="modal calendar-modal"><p class="eyebrow" id="detail-kind"></p><h2 id="detail-title"></h2><p id="detail-time" class="calendar-detail-time"></p><p id="detail-location"></p><div class="detail-actions">${button('Edit','data-detail="edit"')}${button('Review','data-detail="review"')}${button('Complete','data-detail="complete"')}${button('Skip this date','data-detail="skip"')}</div><label>Session notes<textarea id="session-note" rows="6" placeholder="Notes, questions, or what to review…"></textarea></label><p id="detail-status" role="status"></p><div class="form-actions">${button('Close','data-close')}${button('Save note','data-detail="note"')}</div></dialog>
    <dialog id="calendar-review" class="modal calendar-modal"><form id="calendar-review-form"><p class="eyebrow">Spaced review</p><h2 id="review-title">Plan review</h2><label>Days after this session<input name="offsets" value="1, 3, 7" required></label><div class="schedule-fields"><label>Minutes per review<input type="number" name="duration" value="30" min="15" max="180" step="15" required></label><label>From<input type="time" name="from" value="09:00" required></label><label>Until<input type="time" name="until" value="22:00" required></label></div><div id="review-preview"></div><p class="form-error" role="alert"></p><div class="form-actions">${button('Cancel','data-close')}<button type="submit" class="button button-primary" id="review-submit">Find free time</button></div></form></dialog>
    <dialog id="calendar-task" class="modal calendar-modal"><form id="calendar-task-form"><p class="eyebrow">Task</p><h2 id="calendar-task-title">New task</h2><label>Name<input name="title" required maxlength="120"></label><label>Project<select name="project_id"></select></label><div class="schedule-fields"><label>Date<input name="date" type="date"></label><label>Start<input name="time" type="time"></label><label>Minutes<input name="duration" type="number" min="15" max="480" step="15" value="30" required></label><label>Deadline<input name="deadline" type="date"></label></div><p class="form-error" role="alert"></p><div class="form-actions">${button('Cancel','data-close')}<button type="submit" class="button button-primary">Save task</button></div></form></dialog>
    <div class="calendar-toast" role="status" aria-live="polite"></div>`);
  const $=selector=>document.querySelector(selector), formError=(form,message='')=>form.querySelector('.form-error').textContent=message;
  let toastTimer;
  function toast(message){$('.calendar-toast').textContent=message;$('.calendar-toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.calendar-toast').classList.remove('visible'),2400);}
  function write(change){try{const state=getState();change(state);saveState(state);refresh();onChange();return true;}catch(error){toast('Could not save. '+error.message);return false;}}
  document.querySelectorAll('.calendar-modal [data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  function dayButton(day,large=false){const list=entries(day),active=day===selected;return `<button type="button" data-date="${day}" class="month-date ${active?'selected':''} ${day===today?'is-today':''} ${day.slice(0,7)!==month.slice(0,7)?'other-month':''}" aria-label="${label(day,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}" aria-pressed="${active}"><span>${Number(day.slice(8))}</span>${large?`<div class="month-events">${list.slice(0,3).map(e=>`<small class="${color(e)} ${e.completed?'is-complete':''}">${esc(e.title)}</small>`).join('')}${list.length>3?`<em>+${list.length-3}</em>`:''}</div>`:`<i class="month-dot ${list.length?'has-events':''}"></i>`}</button>`;}
  function row(e){return `<div class="calendar-day-row ${e.completed?'is-complete':''}"><span class="calendar-row-time">${e.start_time||'Anytime'}</span><button type="button" class="calendar-item ${color(e)}" data-entry="${e.id}" data-source="${e.source}" data-on="${e.date}"><strong>${esc(e.title)}</strong><small>${esc(e.location||({class:'Class',review:'Review',task:'Task',study:'Study',event:'Personal'}[e.kind]))}</small></button>${e.kind!=='class'?`<button type="button" class="calendar-check" data-complete="${e.id}" data-source="${e.source}" data-on="${e.date}" aria-label="${e.completed?'Reopen':'Complete'} ${esc(e.title)}" aria-pressed="${Boolean(e.completed)}">${e.completed?'✓':'○'}</button>`:''}</div>`;}
  function renderToday(){
    const summary=todaySummary(getState(),userId,today);
    const list=(items,empty)=>items.map(row).join('')||`<p class="calendar-empty">${empty}</p>`;
    const next=summary.next;
    const wasOpen=Object.fromEntries([...root.querySelectorAll('.today-disclosure')].map(el=>[el.id,el.open]));
    $('#today-overview').innerHTML=`<div class="today-toolbar"><span>${summary.tasks.length+summary.reviews.length} to do</span><a class="cal-button" href="index.html">Open calendar ↗</a></div>
      <div class="today-layout"><section class="today-panel today-schedule"><header class="today-section-heading"><h2>Schedule</h2>${button('＋ Event','data-action="new-event"')}</header>
        <div class="today-schedule-list">${list(summary.schedule,'No events scheduled today.')}</div>
        ${next?`<section class="today-next"><p>Coming up · ${label(next.date,{weekday:'short',month:'short',day:'numeric'})}</p>${row(next)}</section>`:''}</section>
      <section class="today-panel today-checklist"><section><header class="today-section-heading"><h2>Tasks <span>${summary.tasks.length}</span></h2>${button('＋','data-action="new-task" aria-label="Add task today"')}</header>${list(summary.tasks,'All caught up.')}</section>
        <section class="today-review"><header class="today-section-heading"><h2>Review <span>${summary.reviews.length}</span></h2></header>${list(summary.reviews,'No reviews due today.')}</section>
        ${summary.overdue.length?`<details class="task-inbox today-disclosure" id="today-overdue" ${wasOpen['today-overdue']?'open':''}><summary>Overdue <span>${summary.overdue.length}</span></summary>${list(summary.overdue,'')}</details>`:''}
        ${summary.completed.length?`<details class="task-inbox today-disclosure" id="today-completed" ${wasOpen['today-completed']?'open':''}><summary>Completed <span>${summary.completed.length}</span></summary>${list(summary.completed,'')}</details>`:''}
      </section></div>`;
  }
  function refresh(){
    if(view==='today'){renderToday();return;}
    const days=weekDates(selected),s=semester();
    $('.mini-month').innerHTML=`<header>${button('‹','data-month="-1" aria-label="Previous month"')}<h2>${label(month,{month:'long',year:'numeric'})}</h2>${button('›','data-month="1" aria-label="Next month"')}</header><div class="mini-weekdays">${['S','M','T','W','T','F','S'].map(d=>`<span>${d}</span>`).join('')}</div><div class="mini-days">${monthDays(month).map(d=>dayButton(d)).join('')}</div>`;
    $('#selected-day-label').textContent=label(selected,{weekday:'short',month:'short',day:'numeric'});
    const list=entries(selected);$('#selected-day-items').innerHTML=list.map(row).join('')||'<p class="calendar-empty">A clear day.</p>';
    const late=ownedTasks().filter(t=>!t.completed&&((t.due_date&&t.due_date<today)||(t.planned_date&&t.planned_date<today)));$('#calendar-overdue').hidden=!late.length;$('#calendar-overdue-count').textContent=late.length;$('#calendar-overdue-list').innerHTML=late.map(t=>row({...t,source:'task',kind:'task',date:t.planned_date||t.due_date})).join('');
    const inbox=ownedTasks().filter(t=>!t.completed&&!t.planned_date&&(!query||t.title.toLocaleLowerCase().includes(query)));
    $('#inbox-count').textContent=inbox.length;$('#inbox-list').innerHTML=inbox.map(t=>row({...t,source:'task',kind:'task',date:selected})).join('')||'<p class="calendar-empty">All caught up.</p>';
    $('#calendar-subtitle').textContent=mode==='week'?'Weekly timetable':mode==='month'?'Monthly overview':'Daily list';
    $('#calendar-period').textContent=mode==='month'?label(month,{month:'long',year:'numeric'}):label(days[0])+' — '+label(days[6]);
    $('#semester-caption').textContent=label(s.start)+' — '+label(s.end)+' · '+s.end.slice(0,4);
    root.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
    root.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));
    const grid=$('#semester-grid'), previous=grid.querySelector('.semester-time-scroll'),top=previous?.scrollTop,left=previous?.scrollLeft;
    if(mode==='month')grid.innerHTML=`<div class="full-month"><div class="month-weekdays">${weekdays.map(d=>`<span>${d}</span>`).join('')}</div><div class="full-month-days">${monthDays(month).slice(0,monthDays(month)[35].slice(0,7)===month.slice(0,7)?42:35).map(d=>dayButton(d,true)).join('')}</div></div>`;
    else if(mode==='agenda')grid.innerHTML=`<div class="semester-agenda">${days.map(day=>`<section><h3><button data-date="${day}">${label(day,{weekday:'short',month:'short',day:'numeric'})}</button></h3>${entries(day).map(row).join('')||'<p class="calendar-empty">No events.</p>'}</section>`).join('')}</div>`;
    else{
      const events=days.map(day=>entries(day));
      grid.innerHTML=`<div class="semester-time-scroll" tabindex="0" aria-label="24-hour weekly timetable"><div class="semester-time-grid"><div class="semester-corner"></div>${days.map(day=>`<button class="semester-day ${day===today?'is-today':''} ${day===selected?'selected':''}" data-date="${day}"><span>${label(day,{weekday:'short'})}</span><strong>${Number(day.slice(8))}</strong></button>`).join('')}<div class="semester-hours">${Array.from({length:25},(_,i)=>`<span style="top:${i*52}px;${i===24?'transform:translateY(-100%)':''}">${String(i).padStart(2,'0')}:00</span>`).join('')}</div>${days.map((day,i)=>{
        const timed=events[i].filter(e=>e.start_time).map(e=>({...e,completed:false,planned_date:day,duration_minutes:minutes(e.end_time)-minutes(e.start_time)}));
        return `<div class="semester-column" data-slot-date="${day}" aria-label="${day}">${timedEvents(timed,day).map(({task:e,start,end,lane,lanes})=>{const original=events[i].find(x=>x.id===e.id);return `<button class="semester-block ${color(e)} ${original.completed?'is-complete':''} kind-${e.kind}" data-entry="${e.id}" data-source="${e.source}" data-on="${day}" style="top:${start*52/60}px;height:${Math.max(22,(end-start)*52/60)}px;left:${lane*100/lanes}%;width:${100/lanes}%" title="${esc(e.title)} · ${e.start_time}–${e.end_time}"><strong>${esc(e.title)}</strong><span>${esc(e.location||'')}</span><small>${e.start_time}–${e.end_time}</small></button>`;}).join('')}</div>`;
      }).join('')}</div></div>`;
      const scroll=grid.querySelector('.semester-time-scroll');scroll.scrollTop=top??8*52;scroll.scrollLeft=left||0;
    }
    root.dataset.mode=mode;
  }
  function selectDate(day){selected=day;month=day.slice(0,7)+'-01';refresh();}
  function moveMonth(amount){const d=new Date(month+'T12:00:00');d.setMonth(d.getMonth()+amount);month=dateKey(d);if(mode==='month')selected=month;refresh();}
  function findEntry(id,source,day){return source==='task'?ownedTasks().find(e=>e.id===id):dayEntries(getState(),userId,day).find(e=>e.id===id&&e.source==='event');}
  function complete(entry){write(s=>{if(entry.source==='task'){const t=s.tasks.find(t=>t.id===entry.id&&t.user_id===userId);t.completed=!t.completed;t.updated_at=new Date().toISOString();}else{const e=s.calendar_events.find(e=>e.id===entry.id&&e.user_id===userId);e.completed_dates=e.completed_dates||[];e.completed_dates=e.completed_dates.includes(entry.date)?e.completed_dates.filter(d=>d!==entry.date):[...e.completed_dates,entry.date];}});}
  function openDetail(entry){current=entry;$('#detail-kind').textContent=entry.kind||'Task';$('#detail-title').textContent=entry.title;$('#detail-time').textContent=label(entry.date,{weekday:'long',month:'long',day:'numeric'})+(entry.start_time?' · '+entry.start_time+(entry.end_time?'–'+entry.end_time:''):'');$('#detail-location').textContent=entry.location||'';$('#session-note').value=(getState().notes||[]).find(n=>n.id===noteId(entry)&&n.user_id===userId)?.body||'';$('#detail-status').textContent='';$('[data-detail="complete"]').hidden=entry.kind==='class';$('[data-detail="complete"]').textContent=entry.completed?'Reopen':'Complete';$('[data-detail="skip"]').hidden=entry.source!=='event';$('[data-detail="review"]').hidden=entry.kind==='review';$('#calendar-detail').showModal();}
  function noteId(e){return 'session:'+e.id+':'+e.date;}
  function openEvent(event=null,prefill={}){editing=event;const form=$('#semester-event-form'),s=semester();form.reset();formError(form);const e=event||{title:'',kind:'class',location:'',first_date:selected,last_date:s.end,start_time:'09:00',end_time:'10:00',repeat:'weekly',weekday:new Date(selected+'T12:00:00').getDay(),color:0,...prefill};for(const key of ['title','kind','location','first_date','last_date','start_time','end_time','repeat','weekday','color'])form.elements[key].value=e[key]??'';$('#event-editor-title').textContent=event?'Edit series':'New event';$('#pause-series').hidden=!event;$('#pause-series').textContent=event?.deleted_at?'Restore series':'Pause series';$('#restore-skipped').hidden=!event?.excluded_dates?.length;syncRecurrence();$('#semester-event').showModal();}
  $('#pause-series').onclick=()=>{if(editing&&write(s=>{const event=s.calendar_events.find(e=>e.id===editing.id&&e.user_id===userId);event.deleted_at=event.deleted_at?null:new Date().toISOString();})){$('#semester-event').close();toast(editing.deleted_at?'Series restored':'Series paused');}};
  $('#restore-skipped').onclick=()=>{if(editing&&write(s=>{s.calendar_events.find(e=>e.id===editing.id&&e.user_id===userId).excluded_dates=[];})){$('#semester-event').close();toast('Skipped dates restored');}};
  function syncRecurrence(){const f=$('#semester-event-form');f.querySelectorAll('.recurrence-field').forEach(el=>el.hidden=f.elements.repeat.value==='none');f.elements.weekday.disabled=f.elements.repeat.value!=='weekly';}
  $('#semester-event-form').elements.repeat.onchange=syncRecurrence;
  $('#semester-event-form').elements.first_date.onchange=e=>{$('#semester-event-form').elements.weekday.value=new Date(e.target.value+'T12:00:00').getDay();};
  $('#semester-event-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form));try{const item=validateEvent({...editing,...data,id:editing?.id||id(),user_id:userId,title:data.title.trim(),color:Number(data.color),weekday:data.repeat==='weekly'?Number(data.weekday):new Date(data.first_date+'T12:00:00').getDay(),last_date:data.repeat==='none'?data.first_date:data.last_date});if(write(s=>{s.calendar_events=s.calendar_events||[];const index=s.calendar_events.findIndex(e=>e.id===item.id&&e.user_id===userId);if(index<0)s.calendar_events.push(item);else s.calendar_events[index]=item;})){form.closest('dialog').close();toast('Event saved');}}catch(error){formError(form,error.message);}};
  function openTask(task=null,date=selected,time=''){editing=task;const form=$('#calendar-task-form');form.reset();formError(form);form.elements.project_id.innerHTML='<option value="">Personal</option>'+getState().projects.filter(p=>p.user_id===userId&&!p.is_personal_inbox&&(p.status!=='archived'||p.id===task?.project_id)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');for(const [key,value] of Object.entries({title:task?.title||'',project_id:task?.project_id||'',date:task?task.planned_date||'':date,time:task?.start_time||time,duration:task?.duration_minutes||30,deadline:task?.due_date||''}))form.elements[key].value=value;$('#calendar-task-title').textContent=task?'Edit task':'New task';$('#calendar-task').showModal();}
  function personalProject(s){let p=s.projects.find(p=>p.user_id===userId&&p.is_personal_inbox&&p.status!=='archived');if(!p){p={id:id(),user_id:userId,name:'Personal',goal:'',project_type:'personal',is_personal_inbox:true,status:'active',created_at:new Date().toISOString()};s.projects.push(p);}return p;}
  $('#calendar-task-form').onsubmit=event=>{event.preventDefault();const form=event.currentTarget,d=Object.fromEntries(new FormData(form)),duration=Number(d.duration);if(!d.title.trim()||(d.time&&!d.date)){formError(form,'Enter a name and choose a date for a timed task.');return;}if(!Number.isInteger(duration)||duration<15||duration>480||(d.time&&minutes(d.time)+duration>1440)){formError(form,'Use 15–480 minutes and finish within the same day.');return;}if(write(s=>{const project=s.projects.find(p=>p.id===d.project_id&&p.user_id===userId)||personalProject(s),existing=editing?s.tasks.find(t=>t.id===editing.id&&t.user_id===userId):null;const task={...existing,id:existing?.id||id(),user_id:userId,project_id:project.id,title:d.title.trim(),planned_date:d.date||null,start_time:d.time||null,duration_minutes:duration,due_date:d.deadline||null,priority:existing?.priority||'medium',completed:existing?.completed||false,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(existing)Object.assign(existing,task);else s.tasks.push(task);})){form.closest('dialog').close();toast('Task saved');}};
  function openSemester(){const s=semester(),form=$('#semester-settings-form');form.elements.start.value=s.start;form.elements.end.value=s.end;formError(form);$('#semester-class-list').innerHTML=(getState().calendar_events||[]).filter(e=>e.user_id===userId).map(e=>`<button type="button" class="semester-class-edit ${color(e)}" data-series="${e.id}"><span>${esc(e.title)}</span><small>${e.deleted_at?'Paused · ':''}${weekdays[e.weekday]} · ${e.start_time}–${e.end_time}</small></button>`).join('')||'<p class="calendar-empty">No classes yet.</p>';$('#semester-settings').showModal();}
  $('#semester-settings-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,start=f.elements.start.value,end=f.elements.end.value;try{validateEvent({title:'Semester',first_date:start,last_date:end,repeat:'weekly',kind:'class',weekday:1,start_time:'09:00',end_time:'10:00'});if(write(s=>{s.settings=s.settings||{};s.settings[userId]={...s.settings[userId],semester:{start,end}};for(const event of s.calendar_events||[])if(event.user_id===userId&&event.kind==='class'&&event.repeat!=='none'){event.first_date=start;event.last_date=end;}})){f.closest('dialog').close();toast('Semester saved');}}catch(error){formError(f,error.message);}};
  $('#semester-class-list').onclick=e=>{const b=e.target.closest('[data-series]');if(b){$('#semester-settings').close();openEvent((getState().calendar_events||[]).find(e=>e.id===b.dataset.series&&e.user_id===userId));}};
  let importRows=null;
  function resetImport(){importRows=null;$('#import-preview').innerHTML='';$('#import-submit').textContent='Preview';}
  $('#semester-import-form').oninput=resetImport;
  $('#semester-import-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;try{if(!importRows){importRows=parseTimetable(f.elements.rows.value,f.elements.start.value,f.elements.end.value);$('#import-preview').innerHTML=importRows.map(r=>`<div class="import-row"><strong>${esc(r.title)}</strong><span>${weekdays[r.weekday]} ${r.start_time}–${r.end_time} · ${esc(r.location)}</span></div>`).join('');$('#import-submit').textContent='Add '+importRows.length+' events';formError(f);return;}let added=0;if(write(s=>{s.calendar_events=s.calendar_events||[];for(const row of importRows){if(s.calendar_events.some(e=>e.user_id===userId&&!e.deleted_at&&e.title===row.title&&e.weekday===row.weekday&&e.start_time===row.start_time&&e.end_time===row.end_time&&e.first_date===row.first_date&&e.last_date===row.last_date))continue;const same=s.calendar_events.find(e=>e.user_id===userId&&e.title===row.title);s.calendar_events.push({...row,color:same?.color??row.color,id:id(),user_id:userId});added++;}s.settings=s.settings||{};s.settings[userId]={...s.settings[userId],semester:{start:f.elements.start.value,end:f.elements.end.value}};})){f.closest('dialog').close();toast(added+' events added');}}catch(error){formError(f,error.message);}};
  const reviewForm=$('#calendar-review-form');let reviewReady=false;
  reviewForm.oninput=event=>{if(event.target.matches('[data-review-index]'))return;reviewReady=false;$('#review-submit').textContent='Find free time';$('#review-preview').innerHTML='';};
  reviewForm.onsubmit=e=>{e.preventDefault();try{const opts={offsets:reviewForm.elements.offsets.value.split(',').map(x=>Number(x.trim())),duration:Number(reviewForm.elements.duration.value),from:reviewForm.elements.from.value,until:reviewForm.elements.until.value};if(!reviewReady){reviews=reviewPlan(getState(),userId,current,current.date,opts);$('#review-preview').innerHTML=reviews.map((r,i)=>`<label class="review-row"><input type="checkbox" data-review-index="${i}" ${r.time?'checked':'disabled'}><span><strong>${label(r.date,{weekday:'short',month:'short',day:'numeric'})}</strong><small>${r.time?r.time+' · '+r.duration+' min':r.reason}</small></span><em>Day ${r.offset}</em></label>`).join('');$('#review-submit').textContent='Add selected reviews';reviewReady=true;formError(reviewForm);return;}const chosen=[...reviewForm.querySelectorAll('[data-review-index]:checked')].map(el=>reviews[Number(el.dataset.reviewIndex)]);if(!chosen.length){formError(reviewForm,'Select at least one available review.');return;}const fresh=reviewPlan(getState(),userId,current,current.date,opts);if(chosen.some(r=>!fresh.some(x=>x.key===r.key&&x.time===r.time))){reviewReady=false;formError(reviewForm,'Your calendar changed. Find free time again.');$('#review-submit').textContent='Find free time';return;}if(write(s=>{const project=personalProject(s);for(const r of chosen)s.tasks.push({id:id(),user_id:userId,project_id:project.id,title:current.title+' · Review '+r.offset,planned_date:r.date,due_date:r.date,start_time:r.time,duration_minutes:r.duration,review_key:r.key,color:current.color??2,priority:'medium',completed:false,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});})){reviewForm.closest('dialog').close();toast(chosen.length+' reviews added');}}catch(error){formError(reviewForm,error.message);}};
  $('#calendar-detail').addEventListener('click',e=>{const action=e.target.closest('[data-detail]')?.dataset.detail;if(!action)return;if(action==='edit'){$('#calendar-detail').close();current.source==='task'?openTask(current):openEvent((getState().calendar_events||[]).find(e=>e.id===current.id&&e.user_id===userId));}if(action==='complete'){complete(current);$('#calendar-detail').close();}if(action==='skip'){if(write(s=>{const item=s.calendar_events.find(e=>e.id===current.id&&e.user_id===userId);item.excluded_dates=[...new Set([...(item.excluded_dates||[]),current.date])];})){$('#calendar-detail').close();toast('Skipped this date');}}if(action==='note'){try{saveState(writeNote(getState(),userId,noteId(current),{title:current.title+' · '+current.date,body:$('#session-note').value,deleted_at:null}));$('#detail-status').textContent='Saved in Notes';}catch{$('#detail-status').textContent='Could not save. Please keep this window open.';}}if(action==='review'){$('#calendar-detail').close();reviewForm.reset();reviewReady=false;$('#review-preview').innerHTML='';$('#review-submit').textContent='Find free time';$('#review-title').textContent=current.title;formError(reviewForm);$('#calendar-review').showModal();}});
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.date){selectDate(b.dataset.date);if(mode==='month'&&matchMedia('(max-width:800px)').matches)document.querySelector('.selected-day').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});return;}if(b.dataset.month){moveMonth(Number(b.dataset.month));return;}if(b.dataset.mode){mode=b.dataset.mode;refresh();return;}if(b.dataset.kind){kind=b.dataset.kind;refresh();return;}if(b.dataset.entry||b.dataset.complete){const day=b.dataset.on,source=b.dataset.source,item=findEntry(b.dataset.entry||b.dataset.complete,source,day);if(item){const entry={...item,date:day,source,kind:item.kind||(item.review_key?'review':'task')};b.dataset.complete?complete(entry):openDetail(entry);}return;}
    const action=b.dataset.action;if(action==='previous'||action==='next'){const step=action==='previous'?-1:1;if(mode==='month')moveMonth(step);else selectDate(shiftDate(selected,step*7));}if(action==='today'){selectDate(today);const scroll=$('.semester-time-scroll');if(scroll)scroll.scrollTop=Math.max(0,(new Date().getHours()-2)*52);}if(action==='semester')openSemester();if(action==='new-event')openEvent();if(action==='new-task')openTask();if(action==='import'){const f=$('#semester-import-form'),s=semester();f.reset();f.elements.start.value=s.start;f.elements.end.value=s.end;formError(f);resetImport();$('#semester-import').showModal();}});
  // A blank cell opens the same editor as the keyboard-accessible + Task action.
  root.addEventListener('dblclick',e=>{const column=e.target.closest('[data-slot-date]');if(column&&!e.target.closest('button')){const minute=Math.min(1410,Math.floor((e.clientY-column.getBoundingClientRect().top)/52*4)*15);openTask(null,column.dataset.slotDate,clock(Math.max(0,minute)));}});
  $('#calendar-search').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase();refresh();};
  $('#quick-task-open').onclick=()=>openTask();
  window.addEventListener('storage',e=>{if(e.key==='projectflow-demo-state')refresh();});
  refresh();return {refresh};
}
