const STORAGE_KEY = 'projectflow-demo-state';
const SESSION_KEY = 'projectflow-demo-session';
const initialState = { users: [], projects: [], tasks: [], issues: [], settings: {} };

export function getState() { return JSON.parse(localStorage.getItem(STORAGE_KEY) || JSON.stringify(initialState)); }
export function saveState(state) { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
export function getSession() { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); }
export function setSession(session) { session ? localStorage.setItem(SESSION_KEY, JSON.stringify(session)) : localStorage.removeItem(SESSION_KEY); }
export function id() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
export function requireSession() { if (!getSession()) { location.href = 'login.html'; return null; } return getSession(); }
export function todayKey(date = new Date()) { return new Date(date).toISOString().slice(0, 10); }
export function addDays(date, amount) { const result = new Date(`${date}T12:00:00`); result.setDate(result.getDate() + amount); return todayKey(result); }
export function getSettings(userId) { const state = getState(); return state.settings?.[userId] || { daily_task_limit: 3, weekend_planning: true, default_project_type: 'personal', default_task_priority: 'medium', ai_starter_enabled: true }; }
export function getProjectTypes(userId) { const settings = getSettings(userId); return settings.project_types || [{ key: 'school', label: '학교', color: '#3f6fd1' }, { key: 'home', label: '집', color: '#3d8b68' }, { key: 'work', label: '업무', color: '#c47b2c' }, { key: 'study', label: '공부', color: '#7658b5' }, { key: 'development', label: '개발', color: '#2457c5' }, { key: 'research', label: '연구', color: '#238b91' }, { key: 'content', label: '콘텐츠', color: '#c85d65' }, { key: 'personal', label: '개인', color: '#65717e' }, { key: 'other', label: '기타', color: '#89929d' }]; }
export function saveSettings(userId, settings) { const state = getState(); state.settings = state.settings || {}; state.settings[userId] = { ...getSettings(userId), ...settings }; saveState(state); }
export function seedDemo() { const state = getState(); if (state.projects.length) return; const projectId = id(); const today = todayKey(); state.settings.demo = getSettings('demo'); state.projects.push({ id: projectId, user_id: 'demo', name: 'AI News Pipeline', description: '개인 뉴스 자동화 프로젝트', project_type: 'development', goal: 'AI 뉴스를 자동 수집하고 분석하여 매주 읽을 수 있는 리포트를 완성한다.', due_date: addDays(today, 12), status: 'active', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }); ['RSS collector 연결','기사 요약 프롬프트 설계','CSV export 구현','JSONL export','README 실행 방법 보완'].forEach((title, index) => state.tasks.push({ id: id(), project_id: projectId, user_id: 'demo', title, priority: index < 2 ? 'high' : 'medium', completed: index < 3, planned_date: index === 3 ? today : addDays(today, index + 1), due_date: addDays(today, index + 4), created_at: new Date().toISOString(), updated_at: new Date().toISOString() })); state.issues.push({ id: id(), project_id: projectId, user_id: 'demo', content: '일부 수집 데이터의 날짜 정보가 누락됨', severity: 'high', status: 'open', created_at: new Date().toISOString() }); saveState(state); }
export function projectProgress(projectId, state = getState()) { const tasks = state.tasks.filter(task => task.project_id === projectId); return tasks.length ? Math.round(tasks.filter(task => task.completed).length / tasks.length * 100) : 0; }
export function logout() { setSession(null); location.href = 'login.html'; }
export function wireLogout() { document.querySelectorAll('[data-logout]').forEach(button => button.addEventListener('click', logout)); if (document.body.dataset.page !== 'login' && !document.querySelector('.workspace-sidebar')) { document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="css/style.css?v=2"><link rel="stylesheet" href="css/v12.css?v=1"><link rel="stylesheet" href="css/calendar.css?v=1"><link rel="stylesheet" href="css/settings.css?v=1"><link rel="stylesheet" href="css/roles.css?v=1">'); const page = document.body.dataset.page; const active = page === 'archive' ? 'archive' : page === 'dashboard' ? 'dashboard' : page === 'settings' ? 'settings' : 'projects'; document.body.insertAdjacentHTML('afterbegin', `<aside class="workspace-sidebar"><a class="sidebar-brand" href="index.html"><span class="brand-mark">PF</span><span>ProjectFlow</span></a><p class="sidebar-label">WORKSPACE</p><nav><a class="sidebar-link ${active === 'dashboard' ? 'selected' : ''}" href="index.html">대시보드</a><a class="sidebar-link ${active === 'projects' ? 'selected' : ''}" href="index.html">프로젝트</a><a class="sidebar-link ${active === 'archive' ? 'selected' : ''}" href="archive.html">보관함</a><a class="sidebar-link ${active === 'settings' ? 'selected' : ''}" href="settings.html">설정</a></nav><div class="sidebar-footer"><span class="sidebar-status">개인 워크스페이스</span><button class="sidebar-logout" data-logout>로그아웃</button></div></aside>`); const sidebarLogout = document.querySelector('.sidebar-logout'); if (sidebarLogout) sidebarLogout.addEventListener('click', logout); } }
export function escapeHtml(value = '') { return value.replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char])); }
